version: '3.9'
services:
  proxy:
    container_name: nginx_proxy 
    build: 
      context: proxy
      dockerfile: Dockerfile
    restart: always
    networks:
      - app
    ports:
      - 80:80
    links:
      - backend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  db:
    container_name: postgres_db 
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      APP_DB_USER: postgres
      APP_DB_PASS: password
      APP_DB_NAME: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  backend:
    build: 
      context: golang
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - app
    environment:
      RDS_HOSTNAME: db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
      mode: replicated
      replicas: 4
      placement:
        max_replicas_per_node: 1
      endpoint_mode: dnsrr
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
