version: '3.5'
services:
  db:
    container_name: postgres_db 
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      APP_DB_USER: adm
      APP_DB_PASS: pass
      APP_DB_NAME: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

    networks:
      - backend
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  backend:
    build: 
      context: goland
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      RDS_HOSTNAME: db
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

networks:
  backend:
