version: '3.5'
services:
  proxy:
    container_name: nginx_proxy 
    build: 
      context: proxy
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - app
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  db:
    container_name: postgres_db 
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      APP_DB_USER: postgres
      APP_DB_PASS: password
      APP_DB_NAME: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  backend:
    build: 
      context: golang
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      RDS_HOSTNAME: db
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
